### ISSUE TITLE
ocr用不了

### ISSUE THREAD

**Issue by bukaixyz** [sml2h3/ddddocr#141]
Traceback (most recent call last):
  File "C:\Users\bukai\PycharmProjects\pythonProject\fuck.py", line 8, in <module>
    res = ocr.classification(image)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bukai\PycharmProjects\pythonProject\venv\Lib\site-packages\ddddocr\__init__.py", line 466, in classification
    image = image.resize((int(image.size[0] * (64 / image.size[1])), 64), Image.ANTIALIAS).convert('L')
                                                                          ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

**Comment by bukaixyz** [comment]
现在好了
