### ISSUE TITLE
1.4.9 滑块匹配报错

### ISSUE THREAD

**Issue by enternal111** [sml2h3/ddddocr#153]
Traceback (most recent call last):
  File ".py", line 28, in <module>
    res = det.slide_match(target_bytes, background_bytes)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ddddocr\__init__.py", line 1699, in slide_match
    target, target_x, target_y = self.get_target(target_bytes)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ddddocr\__init__.py", line 1676, in get_target
    if p[-1] == 0:
       ~^^^^
TypeError: 'int' object is not subscriptable

**Comment by HanMinge** [comment]
我也是这个问题，请问你解决了嘛
